config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'db_info' => 'welcome#db_info'

  get 'course_overview' => 'welcome#course_overview'

  get 'sub_landing' => 'welcome#sub_landing'

  post 'auth' => 'welcome#auth'

  get 'major_requirement' => 'welcome#major_requirement'

  post 'login' => 'welcome#login'

  get 'login' => 'welcome#login'

  get 'profile' => 'welcome#profile'

  #set the root location
  root 'welcome#login'

end

app/views/layouts/_course_overview_query_form.html.erb
<div class="container query_form">
  <%= form_tag( course_overview_path, method: "get" ) do %>

  <div>
  <%= label_tag(:term, "Term: ", class: "query_tag") %>
  <%= select_tag :term, options_for_select(@info['terms'], :selected => params['term'] ), class: "query_options" %>
  </div>

  <div>
  <%= label_tag(:major, "Degree: ", class: "query_tag") %>
  <%= select_tag :major, options_for_select(Major.distinct.order(:name).pluck(:name), :selected => params['major']), class: "query_options" %>
  <%= select_tag :catalog_year, options_for_select(Major.distinct.order(catalogYear: :desc).pluck(:catalogYear), :selected => params['catalog_year']), class: "query_options" %>
  </div>

  <%= submit_tag("Submit", class: "btn btn-large login_btn query_submit" ) %>

  <% end %>
</div>

app/views/layouts/_major_requirement_form.html.erb
<div class="container query_form">
<%= form_tag( major_requirement_path, method: "get" ) do %>

<%= label_tag(:major, "Degree: ", class: "query_tag") %>
<%= select_tag :major, options_for_select(Major.distinct.order(:name).pluck(:name), :selected => params['major']), class: "query_options" %>

<%= label_tag(:catalog_year, "Catalog Year: ", class: "query_tag") %>
<%= select_tag :catalog_year, options_for_select(Major.distinct.order(catalogYear: :desc).pluck(:catalogYear), :selected => params['catalog_year']), class: "query_options" %>

<%= submit_tag("Submit", class: "btn btn-large login_btn, query_submit" ) %>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="eng">
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style>
 /* Modify the background color */
    .navbar-custom {
        background-color: #0065BD;
    }
</style>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
  <a class="navbar-brand">QuickReg</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Course Overview", course_overview_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Degree Requirements", major_requirement_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Profile", profile_path, class: "nav-link" %>
      </li>
    </ul>
</div>

<span class="navbar-text">
   <%= session[:current_user_name] %>
</span>


</nav>

<% flash.each do |type, msg| %>
    <% if type == "alert" %>
        <div id='alert_msg' class="alert alert-danger">
    <% elsif type == "success" %>
        <div id='alert_msg' class="alert alert-success">
    <% else %>
        <div id='alert_msg' class="alert alert-primary">
    <% end %>
    <%= msg %>
    </div>
<% end %>

<%= yield %>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>